<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SanphamSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('san_phams')->delete();

        DB::table('san_phams')->truncate();

        DB::table('san_phams')->insert([
            [
                'ten_san_pham'          =>  'Áo cổ tròn ',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://th.bing.com/th/id/OIP.XIwJWaFM399f2oZTVDcaVQHaHa?pid=ImgDet&rs=1",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'Áo thun ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             => "thoi-trang-nu",
                'hinh_anh'          =>  "https://i.pinimg.com/736x/fb/a3/14/fba314917933c96fa66bb33acf8ee24a.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'Quần jean',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://i.pinimg.com/originals/c2/a8/59/c2a859a0ed774b672be6de1ae276f46e.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  ' combo áo Quần jean',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://down-my.img.susercontent.com/file/cfcdbacb00ffbf18c6c127add3222bdb",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'Quần jean',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://down-vn.img.susercontent.com/file/sg-11134201-7rblb-lnvq3cgb8wf25f_tn",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'Quần jean nam phong cách',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://dongphucgiadinh.com/wp-content/uploads/2022/10/ao-essentials-mau-trang-1.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'Quần nam phối màu',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://down-vn.img.susercontent.com/file/sg-11134201-7rblg-lnvq3c7pli1ydf_tn",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'quần áo thun',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://img.alicdn.com/bao/uploaded/i3/1627122961/O1CN01BERJ201XkBQZR2bEA_!!1627122961.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'đồ thun nam ',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://i.pinimg.com/474x/91/39/ac/9139acb6c00ee8c9d19239e55a41a94d.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'đồ thun cao cấp',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://th.bing.com/th/id/OIP.JlkmsRpgqDpW0d-2sIH-owHaHa?w=640&h=640&rs=1&pid=ImgDetMain",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'áo sơ mi nam cao cấp',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://z-shopping.c.yimg.jp/685/43689685/43689685b_14_d_500.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'sơ mi nam họ tiết caro',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://th.bing.com/th/id/OIP.N1-gikuyfPv7dBvtZzYrmwHaHa?w=800&h=800&rs=1&pid=ImgDetMain",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'sơ mi tay ngắn',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://th.bing.com/th/id/OIP.zCJs8Ew4O1C_tDIGnk-xeAHaHa?rs=1&pid=ImgDetMain",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'Sơ mi siêu hót',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://img.fril.jp/img/317977186/l/896171429.jpg?1587460323",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'sơ mi họa tiết thổ cẩm',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://i.pinimg.com/originals/04/6d/6a/046d6a587653529555c5e543ad039de4.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'quần jean cao cấp',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://luvinus.com/wp-content/uploads/2019/01/thoi-trang-nu-mua-dong-2019-8.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'sơ mi trắng',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://thumbnail11.coupangcdn.com/thumbnails/remote/710x710ex/image/retail/images/2022/04/07/10/2/b848a2ad-8944-4e3a-b62c-c8b7b4c875a0.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'Áo Hoodie nữ ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://bizweb.dktcdn.net/100/287/440/products/ao-hoodie-co-non-mau-xam-nu.jpg?v=1609755827503",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'áo khoát nữ lông cừu ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://gd2.alicdn.com/imgextra/i2/2200603597711/O1CN01ndKeUT26pgq4aFRNV_!!2200603597711.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'quần ống rộng ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             => "thoi-trang-nu",
                'hinh_anh'          =>  "https://salt.tikicdn.com/cache/w1200/ts/product/1b/9c/40/c95032e339ad3f67e224a64b7d8ec17b.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo quần áo nữ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://th.bing.com/th/id/OIP.wDwNqWHVwMBOv2zZoiOYqAHaLH?pid=ImgDet&w=600&h=900&rs=1",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo quần áo nữ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://i.pinimg.com/originals/60/cb/a2/60cba2661716f6e8c48f12f7a95269bd.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo quần áo nữ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://z-shopping.c.yimg.jp/769/72852769/72852769b_38_d_500.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo quần áo nữ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://cdn.grail.bz/images/goods/l/tr24/tr24_v12.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo quần áo nữ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://i.pinimg.com/736x/63/dc/74/63dc74bdd4f02af2b477b4563fedcda9.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo quần áo nữ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://z-shopping.c.yimg.jp/534/72158534/72158534b_1_d_500.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo quần áo nữ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://th.bing.com/th/id/OIP.FtGxydGYUQ5iAGA5ZUvkXAHaI4?w=500&h=600&rs=1&pid=ImgDetMain",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo quần áo nữ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://images.wear2.jp/coordinate/YMiJrXJ3/TCUxi3UU/1638322019_500.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo quần áo nữ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://annshop.vn/wp-content/uploads/7403-kem4-3.png",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo quần áo nữ',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://i.pinimg.com/originals/26/88/db/2688dbe40113fb7d3de66c7e54cbe6dd.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'Áo quần nữ tuổi teen',
                'id_danh_muc'  => '2',
                'slug_san_pham'             =>  "thoi-trang-nu",
                'hinh_anh'          =>  "https://icdn.dantri.com.vn/thumb_w/640/2020/11/12/dantri-thoi-trang-nu-ha-thu-nang-tho-hien-dai-va-khi-chat-finaldocx-1605167916250.jpeg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],

            [
                'ten_san_pham'          =>  'áo hoodie nam ',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://th.bing.com/th/id/OIP.raHueH2m_QEh_ONHQt6V7QHaHa?rs=1&pid=ImgDetMain",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],

            [
                'ten_san_pham'          =>  'Combo đồ yếm cho bé  ',
                'id_danh_muc'  => '3',
                'slug_san_pham'             =>  "thoi-trang-tre-em",
                'hinh_anh'          =>  "https://cf.shopee.vn/file/3981e2171abe8d71682f8a0ee462e77d",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho các bé không lo kích ứng da mẩn đỏ và thoáng mát",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'váy xinh baby  ',
                'id_danh_muc'  => '3',
                'slug_san_pham'             => "thoi-trang-tre-em",
                'hinh_anh'          =>  "https://i.pinimg.com/originals/02/9a/e0/029ae0fa7ce9529a0e8b17d15c59ede0.jpg",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo cây móc đồ  ',
                'id_danh_muc'  => '3',
                'slug_san_pham'             =>  "thoi-trang-tre-em",
                'hinh_anh'          =>  "https://th.bing.com/th/id/R.92a05876998a8473d759818c292e040f?rik=13dsIbuvUMNg0Q&pid=ImgRaw&r=0",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "dể dàng tháo ráp và tiện lợi với mọi không gian",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'tủ đồ bé xinh ',
                'id_danh_muc'  => '3',
                'slug_san_pham'             => "thoi-trang-tre-em",
                'hinh_anh'          =>  "https://cf.shopee.vn/file/bfc9a1ee0915e2f573b7d9d138e78c5d",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có các ngăn kéo rộng rải thiết kế bằng nhựa không gây ẩm ướt đồ",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'áo thun  ',
                'id_danh_muc'  => '1',
                'slug_san_pham'             =>  "thoi-trang-nam",
                'hinh_anh'          =>  "https://th.bing.com/th/id/R.47bb77440f48e4fcf4a6786a42191108?rik=wRvvaiFO00YPag&pid=ImgRaw&r=0",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo vệ sinh chó bé  ',
                'id_danh_muc'  => '3',
                'slug_san_pham'             => "thoi-trang-tre-em",
                'hinh_anh'          =>  "https://th.bing.com/th/id/OIP.pYEYfftt1roIyIVErzxW3AHaFj?pid=ImgDet&rs=1",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'combo đồ cute  ',
                'id_danh_muc'  => '3',
                'slug_san_pham'             => "thoi-trang-tre-em",
                'hinh_anh'          =>  "https://th.bing.com/th/id/OIP.uTkjVDmf54hvinG2mRuzlwHaHa?pid=ImgDet&rs=1",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'          =>  'váy caro  ',
                'id_danh_muc'  => '3',
                'slug_san_pham'             =>  "thoi-trang-tre-em",
                'hinh_anh'          =>  "https://th.bing.com/th/id/OIP.mK0PApdYU7vJY-iEGgKNCgHaHa?pid=ImgDet&rs=1",
                'don_gia'           => "100.000",
                'mo_ta'         =>  "có chất liệu thoáng mát thích hợp mặc cho dịp đi chơi đi làm rất cá tính và tôn dáng",
                'trang_thai'          =>  '1',

            ],
            [
                'ten_san_pham'       => 'Giày sneaker',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_sneaker",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-ljkrxdnr5xxeba",
                'don_gia'           => "100",
                'mo_ta'              => "Phù hợp với mọi người đi chơi, đi học, đi làm ,...",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Giày Nam sneaker thể thao Họa Tiết Clothers',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_sneaker",
                'hinh_anh'        => "https://salt.tikicdn.com/cache/w400/ts/product/6e/e6/3f/5e66ad854dc9aa4754c2d233b0868d1a.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Phù hợp với mọi người đi chơi, đi học, đi làm ,...",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Giày Nam sneaker Thể Thao Nam Chống Trượts',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_sneaker",
                'hinh_anh'        => "https://cf.shopee.vn/file/vn-11134201-23020-6g8n0wu6ixnvb4",
                'don_gia'           => "100",
                'mo_ta'              => "Phù hợp với mọi người đi chơi, đi học, đi làm ,...",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Giày Nam Kaiwings',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_kaiwings",
                'hinh_anh'        => "https://kaiwings.vn/upload/product/kw-037/giay-nam-dep-cong-so-cao-cap-chinh-hang-tre-trung.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Giày lười nam vải với thiết kế mới thời trang rất hợp với quần jean hoặc short,",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Giày Nam Kaiwings',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_kaiwings",
                'hinh_anh'        => "https://giaynamvip.com/upload/product/gnk114/thumb/giay-da-nam-cao-cap-da-bo-xuat-du-ca-tinh_x450.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Giày lười nam vải với thiết kế mới thời trang rất hợp với quần jean hoặc short,",
                'trang_thai'         => '1',
            ],


            [
                'ten_san_pham'       => 'Giày Nữ Sinh Nhật Đế Cao Đen Bóng',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nu",
                'hinh_anh'        => "https://i.bbcosplay.com/14109/giay-nu-sinh-den-don-de-4.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Giày lười nam vải với thiết kế mới thời trang rất hợp với quần jean hoặc short,",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Giày lười nữ IELGY',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nu",
                'hinh_anh'        => "https://my-test-11.slatic.net/p/bbe34ca0fa32050e682920c5f0d63f0e.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Giày lười nam vải với thiết kế mới thời trang rất hợp với quần jean hoặc short,",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Giày búp bê nữ lolita',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nu",
                'hinh_anh'        => "https://media.sellycdn.net/files/md_2023_05_20_10_10_25_0700_qWsJOMASUH.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Giày lười nam vải với thiết kế mới thời trang rất hợp với quần jean hoặc short,",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'giày bata nữ dáng basic màu trắng đen',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nu",
                'hinh_anh'        => "https://vn-live-01.slatic.net/p/7bb25b423c3a0a12c5e66f9ae6710bd5.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Giày thể thao nữ đi học giày bata nữ dáng basic màu trắng đen đơn giản đế cao su GENBAG G01",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Giày bốt nữ Hàn Quốc cổ lửng',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nu",
                'hinh_anh'        => "https://cf.shopee.vn/file/sg-11134201-22110-hauluoyh5wjv2d",
                'don_gia'           => "100",
                'mo_ta'              => "Phần thân trên chất da mềm cao cấp đi rất êm chân, mang thoải mái đi lại cả ngày ",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => ' Giày da Aristino ASHR22 màu đen',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nam",
                'hinh_anh'        => "https://aristino.com/Data/ResizeImage/images/product/giay-da/ashr22/_TC_0968x900x900x4.webp",
                'don_gia'           => "100",
                'mo_ta'              => "Phần thân trên chất da mềm cao cấp đi rất êm chân, mang thoải mái đi lại cả ngày ",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => ' Giày thể thao adidas',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nam",
                'hinh_anh'        => "https://anhdep123.com/wp-content/uploads/2021/01/anh-giay-adidas.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Phần thân trên chất da mềm cao cấp đi rất êm chân, mang thoải mái đi lại cả ngày ",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => ' Giày thể thao nữ',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "giay_nu",
                'hinh_anh'        => "https://i.pinimg.com/474x/69/52/ba/6952ba92b2c7c0f6a030174fadcd4076--pink-adidas-shoes-adidas.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Phần thân trên chất da mềm cao cấp đi rất êm chân, mang thoải mái đi lại cả ngày ",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => ' Giày thể thao adidas',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nam",
                'hinh_anh'        => "https://down-id.img.susercontent.com/file/86444a678767b9547897bcb22356939b",
                'don_gia'           => "100",
                'mo_ta'              => "Phần thân trên chất da mềm cao cấp đi rất êm chân, mang thoải mái đi lại cả ngày ",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => ' Giày thể thao adidas',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nam",
                'hinh_anh'        => "https://prices.vn/photos/8/blog/review-giay-nike-nam.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Phần thân trên chất da mềm cao cấp đi rất êm chân, mang thoải mái đi lại cả ngày ",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => ' Giày thể thao adidas',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nam",
                'hinh_anh'        => "https://prices.vn/photos/8/blog/review-giay-nike-nam.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Phần thân trên chất da mềm cao cấp đi rất êm chân, mang thoải mái đi lại cả ngày ",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => ' Giày thể thao adidas',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nam",
                'hinh_anh'        => "https://th.bing.com/th/id/R.5301e0e907d2ecd158ce2efcd956b410?rik=SS9%2fjuL7qklx0A&pid=ImgRaw&r=0",
                'don_gia'           => "100",
                'mo_ta'              => "Phần thân trên chất da mềm cao cấp đi rất êm chân, mang thoải mái đi lại cả ngày ",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => ' Giày thể thao adidas',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Giay_nam",
                'hinh_anh'        => "https://th.bing.com/th/id/OIP.yBsddgDAFwvlOIidbWVwGgHaHa?w=600&h=600&rs=1&pid=ImgDetMain",
                'don_gia'           => "100",
                'mo_ta'              => "Phần thân trên chất da mềm cao cấp đi rất êm chân, mang thoải mái đi lại cả ngày ",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Kính Mát',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/sg-11134201-7rbkj-lm86kgwux7f44d",
                'don_gia'           => "100",
                'mo_ta'              => "Kính Mát Phân Cực Chống Tia uv Ban Ngày Và Ban Đêm Cho Nam Và Nữ",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Kính Giả Cận Nam Nữ Phong Cách Hàn Quốc D169',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-ljicpaoxfgg2e2",
                'don_gia'           => "100",
                'mo_ta'              => "Kính Giả Cận Nam Nữ Phong Cách Hàn Quốc D169",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Giày Nam sneaker Thể Thao Nam Chống Trượts',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://foot.vn/wp-content/uploads/2020/08/giay-sneaker-bi-rong-8.jpg",
                'don_gia'           => "100",
                'mo_ta'              => "Phù hợp với mọi người đi chơi, đi học, đi làm ,...",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Giày Nam sneaker Thể Thao Nam Chống Trượts',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://th.bing.com/th/id/OIP.rZKzz7UH0RT9W3qgZf2LLwHaHa?w=800&h=800&rs=1&pid=ImgDetMain",
                'don_gia'           => "100",
                'mo_ta'              => "Phù hợp với mọi người đi chơi, đi học, đi làm ,...",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Giày Nam sneaker Thể Thao Nam Chống Trượts',
                'id_danh_muc'      => '4',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://cf.shopee.vn/file/vn-11134201-23020-6g8n0wu6ixnvb4",
                'don_gia'           => "100",
                'mo_ta'              => "Phù hợp với mọi người đi chơi, đi học, đi làm ,...",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Kính Mát Gọng Vuông Nhỏ',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/sg-11134201-7qvg9-ljifo4ucs386da",
                'don_gia'           => "100",
                'mo_ta'              => "Kính Mát Gọng Vuông Nhỏ Chống Tia uv Thời Trang Cho Nam Nữ",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Kính Mát Hình Trái Tim',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/sg-11134201-7r98o-lkug5fjw25br0a",
                'don_gia'           => "100",
                'mo_ta'              => "Kính Mát Hình Trái Tim Đính Đá Kim Cương Nhân Tạo Thời Trang Cho Nữ",
                'trang_thai'         => '1',
            ],


            [
                'ten_san_pham'       => 'Kính Mát y2k',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/sg-11134201-7rbm1-llbip7sex4ez15",
                'don_gia'           => "100",
                'mo_ta'              => " Kính Mát y2k Chống Tia uv400 y2k Phong Cách hip hop Cho Nam Và Nữ",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Mắt kính unisex',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/fd8ff000e47e431bab24e539fe79b02d",
                'don_gia'           => "100",
                'mo_ta'              => "Mắt kính unisex hot trend thời trang gọng kính mát nam nữ nhiều màu phong cách",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Kính Mát Không Gọng Hình Bướm',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/sg-11134201-7r98o-lkzceca3sqxz7chttps://down-vn.img.susercontent.com/file/sg-11134201-7r98o-lkzceca3sqxz7c",
                'don_gia'           => "100",
                'mo_ta'              => "Kính Mát Không Gọng Hình Bướm Đính Đá Thời Trang Kính Mát Thời Trang Dự Tiệc Cho Nữ",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Kính Mát tr90',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/sg-11134201-7rbml-lncj4cjswzaoe7",
                'don_gia'           => "100",
                'mo_ta'              => "Kính Mát tr90 Gọng Kim Loại Chống Tia uv400 Thời Trang",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Kính Gập Chống Nắng',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/sg-11134201-22110-za2r29op4akv95",
                'don_gia'           => "100",
                'mo_ta'              => "Kính Chống Nắng Phân Cực Mặt Vuông Gập Lại Được Gọng Hợp Kim Dành Cho Nam Lái Xe Ngoài Trời",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Áo khoác thể thao 3 sọct',
                'id_danh_muc'      => '5',
                'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lklu9mwdrox6b7",
                'don_gia'           => "100",
                'mo_ta'              => "Áo khoác thể thao 3 sọc logo Das chất nỉ bông dày dặn TONGKHOSI",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Áo khoác nỉ nam nữ',
                'id_danh_muc'      => '5',
                'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lnlfxlavu9h6f7",
                'don_gia'           => "100",
                'mo_ta'              => "Áo khoác nỉ nam nữ form rộng phối màu (xám kem hồng) bo gấu tay phồng túi Hộp có dây kéo hàn quốc fammilyshop",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Áo khoác liền mũ chữ N',
                'id_danh_muc'      => '5',
                'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/vn-11134201-23030-wzq9hr29ipov1f",
                'don_gia'           => "100",
                'mo_ta'              => "Áo khoác liền mũ chữ N họa tiết ngôi sao bên tay STYLT MARVEN - AO KHOAC NAM 002",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Áo Khoác jean',
                'id_danh_muc'      => '5',
                'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lm474qm8o8nzf8",
                'don_gia'           => "100",
                'mo_ta'              => "Áo Khoác jean nam nữ Unisex Avocado, áo khoác jacket nam bò form rộng màu Xanh Đen xám trắng",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Áo Khoác Da Lộn',
                'id_danh_muc'      => '5',
                'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/dfd9a2bb75bb9a7d887608b5979980e3",
                'don_gia'           => "100",
                'mo_ta'              => "Áo Khoác Da Lộn Nam Lót Lông Cừu Cổ Cao Đẹp Cao Cấp ABANDON W1",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'ÁO KHOÁT NỈ',
                'id_danh_muc'      => '5',
                'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/vn-11134207-7qukw-lk5h5o2af0l093",
                'don_gia'           => "100",
                'mo_ta'              => "ÁO KHOÁT NỈ PHỐI MÀU THỜI TRANG SIÊU DỄ THƯƠNG",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Áo khoác nữ thun',
                'id_danh_muc'      => '5',
                'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/baa1b22de1bc5324fa7590a258d38f5b",
                'don_gia'           => "100",
                'mo_ta'              => "Áo khoác nữ thun da cá lửng thêu chuột disney",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'ÁO KHOÁC',
                'id_danh_muc'      => '5',
                'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/d4c3d63e14e10d6faba92edbf096b9c4",
                'don_gia'           => "100",
                'mo_ta'              => "ÁO KHOÁC NỈ NGOẠI 3 SỌC SIÊU SÀNH ĐIỆU , CHẤT THUN NỈ NGOẠI DÀY , MỊN UTK",
                'trang_thai'         => '1',
            ],

            [
                'ten_san_pham'       => 'Aó khoác dù Nữ',
               'id_danh_muc'      => '5',
                 'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/5554bc3a30ba945cf29b75cfdcee02d2",
                'don_gia'           => "100",
                'mo_ta'              => "Aó khoác dù Nữ kiểu lửng crotop thiết kế 2 lớp dù có túi trong nhỏ rất tiện lợi hình thêu chữ C bắt trend 2022 UTS",
                'trang_thai'         => '1',
            ],



            [
                'ten_san_pham'       => 'Áo nam len ấm ',
               'id_danh_muc'      => '5',
                 'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://th.bing.com/th/id/OIP.mz3kD1tsd7SSuDqXL33IcwHaHa?pid=ImgDet&w=199&h=199&c=7&dpr=1.5",
                'don_gia'           => "222",
                'mo_ta'              => "Aó khoác dù Nữ kiểu lửng crotop thiết kế 2 lớp dù có túi trong nhỏ rất tiện lợi hình thêu chữ C bắt trend 2022 UTS",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Áo nam khoát len nam  ',
               'id_danh_muc'      => '5',
                 'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://gd1.alicdn.com/imgextra/i3/374335461/O1CN01ix2cqJ1qDBi1aaQfu_!!374335461.jpg_400x400.jpg",
                'don_gia'           => "344",
                'mo_ta'              => "Aó khoác dù Nữ kiểu lửng crotop thiết kế 2 lớp dù có túi trong nhỏ rất tiện lợi hình thêu chữ C bắt trend 2022 UTS",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Áo nam phong cách hàn quốc ',
               'id_danh_muc'      => '5',
                 'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://i.pinimg.com/736x/fe/61/a2/fe61a2437594eef59c43d764bf52f628.jpg",
                'don_gia'           => "353",
                'mo_ta'              => "Aó khoác dù Nữ kiểu lửng crotop thiết kế 2 lớp dù có túi trong nhỏ rất tiện lợi hình thêu chữ C bắt trend 2022 UTS",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Áo nam phong cách hàn quốc ',
               'id_danh_muc'      => '1',
                 'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://img.alicdn.com/bao/uploaded/i2/2130931564/O1CN01H9NHeT1NQMGseYAvl_!!2130931564.jpg",
                'don_gia'           => "211",
                'mo_ta'              => "Aó khoác dù Nữ kiểu lửng crotop thiết kế 2 lớp dù có túi trong nhỏ rất tiện lợi hình thêu chữ C bắt trend 2022 UTS",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Áo nam phong cách quốc ',
               'id_danh_muc'      => '5',
                 'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://img15.shop-pro.jp/PA01155/177/product/167293657_o1.jpg?cmsp_timestamp=20220324104411",
                'don_gia'           => "600",
                'mo_ta'              => "Aó khoác dù Nữ kiểu lửng crotop thiết kế 2 lớp dù có túi trong nhỏ rất tiện lợi hình thêu chữ C bắt trend 2022 UTS",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Áo nam phong cách quốc ',
               'id_danh_muc'      => '1',
                 'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://contents.sixshop.com/thumbnails/uploadedFiles/61788/product/image_1577367520924_1000.jpg",
                'don_gia'           => "213",
                'mo_ta'              => "Aó khoác dù Nữ kiểu lửng crotop thiết kế 2 lớp dù có túi trong nhỏ rất tiện lợi hình thêu chữ C bắt trend 2022 UTS",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Áo nam phong cách quốc ',
               'id_danh_muc'      => '5',
                 'slug_san_pham'      => "Ao_khoat",
                'hinh_anh'        => "https://contents.sixshop.com/thumbnails/uploadedFiles/61788/product/image_1577367520249_2500.jpg",
                'don_gia'           => "434",
                'mo_ta'              => "Aó khoác dù Nữ kiểu lửng crotop thiết kế 2 lớp dù có túi trong nhỏ rất tiện lợi hình thêu chữ C bắt trend 2022 UTS",
                'trang_thai'         => '1',
            ],
            [
                'ten_san_pham'       => 'Gọng Kính Nam',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://vn-live-02.slatic.net/p/8/kinh-gong-tron-nho-nhe-int-1505030933-72210331-3cad24e4c56480963ec8601fa279bce8-catalog_233.jpg_800x800Q100.jpg",
                'don_gia'           => "1500",
                'mo_ta'              => "Gọng Kính Nam A-MO AMO24100 C3",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Gọng Kính Nam',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://kinhmateyeplus.com/wp-content/uploads/2023/06/IMG_0835-600x600.jpg",
                'don_gia'           => "1580",
                'mo_ta'              => "Gọng Kính Nam BOLON BT1605 B11",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Mát tr90',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/sg-11134201-7rbml-lncj4cjswzaoe7",
                'don_gia'           => "1200",
                'mo_ta'              => "Kính Mát tr90 Gọng Kim Loại Chống Tia uv400 Thời Trang",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Mát Nữ',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://phuotstore.net/upload/store/2019-07/mat-kinh-nam-AORON-A599-5.jpg",
                'don_gia'           => "800",
                'mo_ta'              => "Gọng Kính Nữ A-MO AMO24408 C40",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Mát Nữ',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://down-vn.img.susercontent.com/file/sg-11134201-7rbml-lncj4cjswzaoe7",
                'don_gia'           => "750",
                'mo_ta'              => "Kính mát ANCCI Nữ AC201261 M55",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Cận Nữ',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://vn-live-02.slatic.net/p/7/kinh-mat-nu-shady-g244-den-1490001544-5576611-d4d269365be2190d837d8c78f68e4738-catalog_233.jpg_800x800Q100.jpg",
                'don_gia'           => "500",
                'mo_ta'              => "Gọng Kính Nữ A-MO AMO24409 C40",
                'trang_thai'         => '1',
            ],

[
                'ten_san_pham'       => 'Kính Mát Unisex',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://vn-test-11.slatic.net/p/37f62e47fe3e2f11a441eaf3ce351281.jpg_600x600Q100.jpg",
                'don_gia'           => "133",
                'mo_ta'              => "Kính mát ANCCI Unisex AC7109 C3",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Mát Nam',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://salt.tikicdn.com/cache/280x280/ts/product/e6/0d/12/fbfe008dff759b6078cb1e7ef26c708b.JPG",
                'don_gia'           => "880",
                'mo_ta'              => "Kính Mát Nam ANCCI AC201255 M02",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Cận Nữ',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://cdn.tgdd.vn/Products/Images/7678/254230/mat-kinh-thoi-trang-nu-dora-7125-c3-hong-gold-3-1-600x600.jpg",
                'don_gia'           => "750",
                'mo_ta'              => "Gọng Kính Nữ A-MO AMO24409 C34",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Mát Unisex',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://desmonshop.com/wp-content/uploads/2021/11/photo_2021-11-19_11-41-11.jpg",
                'don_gia'           => "950",
                'mo_ta'              => "Kính mát ANCCI Unisex AC7109 C3",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Mát Nam',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://vn-test-11.slatic.net/p/19ffaef9a090d59dfd056b6df27a47e9.jpg",
                'don_gia'           => "700",
                'mo_ta'              => "Kính Mát Nam ARMANI EXCHANGE 0AX2037S 60008160",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Mát Unisex',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://cdn.vuahanghieu.com/unsafe/247x0/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2019/07/kinh-mat-gentle-monster-dal-lake-01-5d201bd1b0e5d-06072019105601.jpg",
                'don_gia'           => "900",
                'mo_ta'              => "Kính mát ANCCI Unisex AC7131 C2",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Cận Nam',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://product.hstatic.net/200000689681/product/1_d65f422fd0584809911838c628f8cea8_master.png",
                'don_gia'           => "1150",
                'mo_ta'              => "Gọng Kính Nam TOMMY HILFIGER TH1945_UNS.C",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Mát Unisex',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://cdn.vuahanghieu.com/unsafe/0x900/left/top/smart/filters:quality(90)/https://admin.vuahanghieu.com/upload/product/2023/10/kinh-mat-nam-tommy-hilfiger-th1978-s_fll-cs-sunglasses-mau-xanh-duong-653f052610084-30102023082142.jpg",
                'don_gia'           => "950",
                'mo_ta'              => "Gọng Kính Nam ANCCI AC50581 GP",
                'trang_thai'         => '1',
            ],
[
                'ten_san_pham'       => 'Kính Mát Nam',
                'id_danh_muc'      => '6',
                'slug_san_pham'      => "Kinh",
                'hinh_anh'        => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_LvhB1B_b4aE0IvWwcbQhe31Sewwty6UpOzWE7ooa-AqqmuhThM1WQsCcueWWhGm3Ybo&usqp=CAU",
                'don_gia'           => "900",
                'mo_ta'              => "Gọng Kính Nam ANCCI AC50581 HJ",
                'trang_thai'         => '1',
            ],

        ]);
    }
}
